services:
  sql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: opti-sql
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
      MSSQL_SA_PASSWORD: "Your_strong_SA_password_123!"
    ports:
      - "14333:1433"
    volumes:
      - opti_sql_data:/var/opt/mssql

volumes:
  opti_sql_data:
